### ISSUE TITLE
Geetest被过滤器误拦截造成的无法显示网页

### ISSUE THREAD

**Issue by LaoshuBaby** [Kamisato-Ayaka-233/HoYoLabPP#3]
## 故障简述

<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/294f5065-4373-47c3-bff9-d9f6cde91789" width="450px">

会这样，全黑

之后在控制台看有这些
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/be4c0cc1-7421-4740-b133-bce2277a5bb9" width="500px">
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/354d68d8-a65a-412f-bea2-4b70bb2fed89" width="500px">
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/54dccf5e-ae83-4477-8442-5944e58d9b3e" width="500px">

## 对照

在没有任何用户脚本的全新profile里面正常打开
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/b90d31db-a43f-4de4-872e-d41efd6ad01d" width="450px">

## 站外讨论

<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/1fdf2e08-55ab-4f68-ba22-51fa87ec933d" width="500px">
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/c9fa737c-c0fc-4c68-84d6-d23ad87bf13c" width="500px">
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/52a834ae-1f57-4a13-b216-c26d486f1c32" width="500px">
<img src="https://github.com/Kamisato-Ayaka-233/HoYoLabPP/assets/42690037/69b2318e-23ba-4431-8cfe-59f2c438b595" width="500px">

站外讨论，懒得重新写issue了就直接贴了（不要打窝，蟹蟹

**Comment by MoRanYue** [comment]
[`f21f1e6`](https://github.com/Kamisato-Ayaka-233/HoYoLabPP/commit/f21f1e6c6c80f1fdb4416ee730633887eaf603b2)

Bug修复已经提交到`dev`分支
